FROM oraclelinux:7-slim

ARG MYSQL_YUM_REPO_URL

RUN yum install -y $MYSQL_YUM_REPO_URL \
    && rpm --import https://repo.mysql.com/RPM-GPG-KEY-mysql-2023 \
    && rpm --import https://repo.mysql.com/RPM-GPG-KEY-mysql-2025 \
    && yum install -y mysql-community-client mysql-router-community libpwquality \
    && yum clean all

COPY mysqlrouter.pwd /mysqlrouter.pwd
COPY run_https.sh /tmp/run.sh
COPY certs/localhost.crt /server.crt
COPY certs/localhost.key /server.key

RUN chmod +x /tmp/run.sh

HEALTHCHECK \
	CMD mysqladmin --port 6446 --protocol TCP ping 2>&1 | grep Access || exit 1

EXPOSE 8443
ENTRYPOINT ["/tmp/run.sh"]
CMD ["mysqlrouter"]